[package]
name = "ocaast"
version = "0.1.0"
edition = "2021"
authors = ["Marcin Olichwiruk <marcin.olichwiruk@opensoftware.pl>", "Robert Mitwicki <robert.mitwicki@opensoftware.pl>", "Michał Pietrus <michal.pietrus@opensoftware.pl>"]
license = "EUPL-1.2"
readme = "README.md"
description = "Library for handling Abstract Syntax Tree of OCA bundle"


[lib]
name = "ocaast"
path = "src/lib.rs"


[dependencies]
thiserror = "1.0.38"
log = "0.4.0"
env_logger = "0.10.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
